# Render Blueprint - Elixir E-commerce
# https://render.com/docs/blueprint-spec

services:
  # Backend Django
  - type: web
    name: elixir-backend
    runtime: python
    region: oregon
    rootDir: Backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn elixir_db.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: DATABASE_URL
        fromDatabase:
          name: elixir-db
          property: connectionString

  # Frontend React
  - type: web
    name: elixir-frontend
    runtime: static
    region: oregon
    rootDir: Frontend/PaginaWeb
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: elixir-db
    databaseName: elixir
    user: elixir_user
    region: oregon


